apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brille-frontend
    team: teamdigihot
  name: hm-brille-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 5000
  ingresses:
    - https://brille.dev.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
      errorPath: ""
  tokenx:
    enabled: true
  env:
    - name: API_URL
      value: 'http://hm-brille-api.teamdigihot.svc.cluster.local'
    - name: API_AUDIENCE
      value: dev-gcp:teamdigihot:hm-brille-api
    - name: PORT
      value: '5000'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      rules:
        - application: hm-brille-api
