apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brille-frontend
    team: teamdigihot
  name: hm-brille-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  team: teamdigihot
  port: 5000
  ingresses:
    - https://brille.labs.nais.io
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  env:
    - name: API_URL
      value: ''
    - name: PORT
      value: '5000'
    - name: USE_MSW
      value: 'true'
    - name: GIT_COMMIT
      value: {{commit}}
