apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-brille-frontend
    team: teamdigihot
  name: hm-brille-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 5000
  ingresses:
    - https://www.nav.no/hjelpemidler/barnebriller
  liveness:
    path: /hjelpemidler/barnebriller/internal/isalive
  readiness:
    path: /hjelpemidler/barnebriller/internal/isready
  prometheus:
    enabled: true
    path: /hjelpemidler/barnebriller/internal/metrics
  replicas:
    max: 4
    min: 2
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 40m
      memory: 512Mi
  secureLogs:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      locale: nb
      autoLogin: true
  tokenx:
    enabled: true
  env:
    - name: BRILLE_API_BASE_URL
      value: 'http://hm-brille-api.teamdigihot.svc.cluster.local'
    - name: BRILLE_API_TARGET_AUDIENCE
      value: prod-gcp:teamdigihot:hm-brille-api
    - name: PORT
      value: '5000'
    - name: GIT_COMMIT
      value: {{commit}}
  accessPolicy:
    outbound:
      rules:
        - application: hm-brille-api
      external:
        - host: www.nav.no
